<a href="https://colab.research.google.com/github/Estibenjcp/Machine-Learning-BootCamp/blob/main/SQLBasics_starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# imports
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
# mount data
from google.colab import drive
drive.mount('/content/drive')

In [2]:
# load data - change the path to match your drive!
df_school = pd.read_csv('School Details.csv')
# make sure it loaded correctly
df_school.head(2)

,DistrictName,EstablishmentCode,EstablishmentName,BRCName,CRCName,SchoolLevel,ManagementName,LocalityHabitation,SubdivisionName,ConstituencyName,...,EstablishedDate,DistrictHQDistance (in Km),CRCDistance (in Km),BACDistance (in Km),IsRecognized,RecognizedBy,ContactPersonName,LowestClass,HighestClass,BoardName
0,East,S0169,BUDANG GOVERNMENT PRIMARY SCHOOL (E),Duga Brc,Central Pendam Government Senior Secondary School,PS,State Govt.,BUDANG,Gangtok,Rhenock,...,28126,58.0,8.0,16.0,Recognized,HRDD,NaN,Class 1,Class 5,NaN
1,East,S0099,CENTRAL PENDAM GOVERNMENT SENIOR SECONDARY SCHOOL,Duga Brc,Central Pendam Government Senior Secondary School,SSS,State Govt.,CENTRAL PENDAM,Gangtok,West Pandam,...,15342,50.0,0.0,6.0,Recognized,HRDD,NaN,Class 1,Class 12,C.B.S.E.

In [3]:
# create sqlite engine
engine = create_engine('sqlite:///schools.db', echo=True)
# create connection to engine
conn = engine.connect()

In [4]:
# add the dataframe as a table in sqlite
sqlite_table = "school_details"
df_school.to_sql(sqlite_table, conn, if_exists='replace')

2024-05-23 19:12:32,872 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2024-05-23 19:12:32,891 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("school_details")

INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("school_details")

2024-05-23 19:12:32,895 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-05-23 19:12:32,898 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("school_details")

INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("school_details")

2024-05-23 19:12:32,902 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-05-23 19:12:32,911 INFO sqlalchemy.engine.Engine
CREATE TABLE school_details (
	"index" BIGINT,
	"DistrictName" TEXT,
	"EstablishmentCode" TEXT,
	"EstablishmentName" TEXT,
	"BRCName" TEXT,
	"CRCName" TEXT,
	"SchoolLevel" TEXT,
	"ManagementName" TEXT,
	"LocalityHabitation" TEXT,
	"SubdivisionName" TEXT,
	"ConstituencyName" TEXT,
	"RevenueBlockName" TEXT,
	"CivicBodyName" TEXT,
	"WardName" TEXT,
	"PostOfficeName" TEXT,
	"PhoneNo" TEXT,
	"FaxNo" TEXT,
	"EmailID" TEXT,
	"Website" TEXT,
	"LocatedInRuralOrUrban" TEXT,
	"DiseCode" TEXT,
	"EstablishedDate" TEXT,
	"DistrictHQDistance (in Km)" FLOAT,
	"CRCDistance (in Km)" FLOAT,
	"BACDistance (in Km)" FLOAT,
	"IsRecognized" TEXT,
	"RecognizedBy" TEXT,
	"ContactPersonName" FLOAT,
	"LowestClass" TEXT,
	"HighestClass" TEXT,
	"BoardName" TEXT
)

INFO:sqlalchemy.engine.Engine:
CREATE TABLE school_details (
	"index" BIGINT,
	"DistrictName" TEXT,
	"EstablishmentCode" TEXT,
	"EstablishmentName" TEXT,
	"BRCName" TEXT,
	"CRCName" TEXT,
	"SchoolLevel" TEXT,
	"ManagementName" TEXT,
	"LocalityHabitation" TEXT,
	"SubdivisionName" TEXT,
	"ConstituencyName" TEXT,
	"RevenueBlockName" TEXT,
	"CivicBodyName" TEXT,
	"WardName" TEXT,
	"PostOfficeName" TEXT,
	"PhoneNo" TEXT,
	"FaxNo" TEXT,
	"EmailID" TEXT,
	"Website" TEXT,
	"LocatedInRuralOrUrban" TEXT,
	"DiseCode" TEXT,
	"EstablishedDate" TEXT,
	"DistrictHQDistance (in Km)" FLOAT,
	"CRCDistance (in Km)" FLOAT,
	"BACDistance (in Km)" FLOAT,
	"IsRecognized" TEXT,
	"RecognizedBy" TEXT,
	"ContactPersonName" FLOAT,
	"LowestClass" TEXT,
	"HighestClass" TEXT,
	"BoardName" TEXT
)

2024-05-23 19:12:32,917 INFO sqlalchemy.engine.Engine [no key 0.00540s] ()

INFO:sqlalchemy.engine.Engine:[no key 0.00540s] ()

2024-05-23 19:12:32,941 INFO sqlalchemy.engine.Engine CREATE INDEX ix_school_details_index ON school_details ("index")

INFO:sqlalchemy.engine.Engine:CREATE INDEX ix_school_details_index ON school_details ("index")

2024-05-23 19:12:32,943 INFO sqlalchemy.engine.Engine [no key 0.00280s] ()

INFO:sqlalchemy.engine.Engine:[no key 0.00280s] ()

2024-05-23 19:12:33,023 INFO sqlalchemy.engine.Engine INSERT INTO school_details ("index", "DistrictName", "EstablishmentCode", "EstablishmentName", "BRCName", "CRCName", "SchoolLevel", "ManagementName", "LocalityHabitation", "SubdivisionName", "ConstituencyName", "RevenueBlockName", "CivicBodyName", "WardName", "PostOfficeName", "PhoneNo", "FaxNo", "EmailID", "Website", "LocatedInRuralOrUrban", "DiseCode", "EstablishedDate", "DistrictHQDistance (in Km)", "CRCDistance (in Km)", "BACDistance (in Km)", "IsRecognized", "RecognizedBy", "ContactPersonName", "LowestClass", "HighestClass", "BoardName") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

INFO:sqlalchemy.engine.Engine:INSERT INTO school_details ("index", "DistrictName", "EstablishmentCode", "EstablishmentName", "BRCName", "CRCName", "SchoolLevel", "ManagementName", "LocalityHabitation", "SubdivisionName", "ConstituencyName", "RevenueBlockName", "CivicBodyName", "WardName", "PostOfficeName", "PhoneNo", "FaxNo", "EmailID", "Website", "LocatedInRuralOrUrban", "DiseCode", "EstablishedDate", "DistrictHQDistance (in Km)", "CRCDistance (in Km)", "BACDistance (in Km)", "IsRecognized", "RecognizedBy", "ContactPersonName", "LowestClass", "HighestClass", "BoardName") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

2024-05-23 19:12:33,031 INFO sqlalchemy.engine.Engine [generated in 0.04855s] [(0, 'East', 'S0169', 'BUDANG GOVERNMENT PRIMARY SCHOOL (E)', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'PS', 'State Govt.', 'BUDANG', 'Gangtok', 'Rhenock', 'Central Pendam', 'Central Pendam', 'Sajong', 'Upper Pendam', None, None, None, None, 'Urban Area', None, '28126', 58.0, 8.0, 16.0, 'Recognized', 'HRDD', None, 'Class 1', 'Class 5', None), (1, 'East', 'S0099', 'CENTRAL PENDAM GOVERNMENT SENIOR SECONDARY SCHOOL', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'SSS', 'State Govt.', 'CENTRAL PENDAM', 'Gangtok', 'West Pandam', 'Central Pendam', 'Central Pendam', 'Karmithang', 'Upper Pendam', '3592263812', None, None, None, 'Urban Area', '800401', '15342', 50.0, 0.0, 6.0, 'Recognized', 'HRDD', None, 'Class 1', 'Class 12', 'C.B.S.E.'), (2, 'East', 'S0848', 'CENTRAL POINT ACADEMY, CENTRAL PENDAM', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'SS', 'Private (Unaided)', 'UPPER BHURUNG CENTRAL PENDAM', 'Gangtok', 'West Pandam', 'Central Pendam', 'Central Pendam', 'Burung', 'Upper Pendam', '03592263809/263960', None, 'ksu_5162@yahoo.com', 'www.facebook.com/khanalkeshav (Group-CPA)', 'Urban Area', None, '37257.38680555556', 49.0, 1.5, 6.0, 'Recognized', 'HRDD, GOVT. OF SIKKIM', None, 'Class 1', 'Class 10', 'C.B.S.E.'), (3, 'East', 'S0190', 'CHEURIBOTEY GOVERNMENT JUNIOR HIGH SCHOOL (E)', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'JHS', 'State Govt.', 'CHEURIBOTEY', 'Gangtok', 'West Pandam', 'Central Pendam', 'Central Pendam', 'Cheuribotey', 'Duga', None, None, None, None, 'Urban Area', None, '28856', 60.0, 6.0, 6.0, 'Recognized', 'State Govt.', None, 'Class 1', 'Class 8', None), (4, 'East', 'S0111', 'DUGA GOVERNMENT SECONDARY SCHOOL', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'SS', 'State Govt.', 'DUGA', 'Gangtok', 'West Pandam', 'Central Pendam', 'Central Pendam', 'Duga', 'Duga', '9832082915', None, 'dugaschool@gmail.com', None, 'Urban Area', None, '1828', 52.0, 0.0, 0.5, 'Recognized', 'c.b.s.e.', None, 'Class 1', 'Class 10', 'C.B.S.E.'), (5, 'East', 'S0856', 'EASWARAMMA SAI GURUKOOL ACCADEMY', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'PS', 'Private (Unaided)', 'RALUNG', 'Gangtok', 'West Pandam', 'Central Pendam', 'West Pendam', 'Ralang', 'West Pendam', '9733056624', None, None, None, 'Urban Area', None, '40179.66805555556', 0.0, 0.2, 0.2, 'Recognized', None, None, 'Class 1', 'Class 5', None), (6, 'East', 'S0870', 'ETERNAL ENGLISH SCHOOL, WEST PENDAM', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'PS', 'Private (Unaided)', 'SAKHU WEST PENDAM', 'Gangtok', 'West Pandam', 'West Pendam', 'West Pendam', 'Sakhu', 'Sakhu Busty', '9734190544', None, None, None, 'Urban Area', None, '37300.66805555556', 42.0, 3.0, 4.0, 'Recognized', 'HRDD OF SIKKIM', None, 'Class 1', 'Class 5', None), (7, 'East', 'S0157', 'KHANI GOAN GOVERNMENT PRIMARY SCHOOL', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'PS', 'State Govt.', 'WEST PENDAM', 'Gangtok', 'West Pandam', 'West Pendam', 'West Pendam', 'Khanigaon', 'West Pendam', '9832470263', None, None, None, 'Urban Area', '801801', '29587', 45.0, 5.0, 4.0, 'Recognized', 'State Govt.', None, 'Class 1', 'Class 5', 'C.B.S.E.')  ... displaying 10 of 1249 total bound parameter sets ...  (1247, 'West', 'S0340', 'TINGTING GAON GOVERNMENT PRIMARY SCHOOL', 'Yuksom Brc', 'Yuksom Government Secondary School', 'PS', 'State Govt.', 'TING TING GAON', 'Gyalshing', 'Yoksam-Tashiding', 'Yoksam', 'Yuksom', 'Tingting', 'Yuksom', '9593377402', None, None, None, 'Urban Area', '100282', '29587', 36.0, 3.0, 6.0, 'Recognized', 'STATE GOVERNMENT', None, 'Class 1', 'Class 5', None), (1248, 'West', 'S0542', 'TSONG GOVERNMENT PRIMARY SCHOOL', 'Yuksom Brc', 'Yuksom Government Secondary School', 'PS', 'State Govt.', 'TSONG', 'Gyalshing', 'Yoksam-Tashiding', 'Yoksam', 'Yuksom', 'Yoksam', 'Yuksom', None, None, None, None, 'Urban Area', None, '28176', 40.0, 7.0, 8.0, 'Recognized', 'State Government', None, 'Class 1', 'Class 5', 'C.B.S.E.')]

INFO:sqlalchemy.engine.Engine:[generated in 0.04855s] [(0, 'East', 'S0169', 'BUDANG GOVERNMENT PRIMARY SCHOOL (E)', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'PS', 'State Govt.', 'BUDANG', 'Gangtok', 'Rhenock', 'Central Pendam', 'Central Pendam', 'Sajong', 'Upper Pendam', None, None, None, None, 'Urban Area', None, '28126', 58.0, 8.0, 16.0, 'Recognized', 'HRDD', None, 'Class 1', 'Class 5', None), (1, 'East', 'S0099', 'CENTRAL PENDAM GOVERNMENT SENIOR SECONDARY SCHOOL', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'SSS', 'State Govt.', 'CENTRAL PENDAM', 'Gangtok', 'West Pandam', 'Central Pendam', 'Central Pendam', 'Karmithang', 'Upper Pendam', '3592263812', None, None, None, 'Urban Area', '800401', '15342', 50.0, 0.0, 6.0, 'Recognized', 'HRDD', None, 'Class 1', 'Class 12', 'C.B.S.E.'), (2, 'East', 'S0848', 'CENTRAL POINT ACADEMY, CENTRAL PENDAM', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'SS', 'Private (Unaided)', 'UPPER BHURUNG CENTRAL PENDAM', 'Gangtok', 'West Pandam', 'Central Pendam', 'Central Pendam', 'Burung', 'Upper Pendam', '03592263809/263960', None, 'ksu_5162@yahoo.com', 'www.facebook.com/khanalkeshav (Group-CPA)', 'Urban Area', None, '37257.38680555556', 49.0, 1.5, 6.0, 'Recognized', 'HRDD, GOVT. OF SIKKIM', None, 'Class 1', 'Class 10', 'C.B.S.E.'), (3, 'East', 'S0190', 'CHEURIBOTEY GOVERNMENT JUNIOR HIGH SCHOOL (E)', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'JHS', 'State Govt.', 'CHEURIBOTEY', 'Gangtok', 'West Pandam', 'Central Pendam', 'Central Pendam', 'Cheuribotey', 'Duga', None, None, None, None, 'Urban Area', None, '28856', 60.0, 6.0, 6.0, 'Recognized', 'State Govt.', None, 'Class 1', 'Class 8', None), (4, 'East', 'S0111', 'DUGA GOVERNMENT SECONDARY SCHOOL', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'SS', 'State Govt.', 'DUGA', 'Gangtok', 'West Pandam', 'Central Pendam', 'Central Pendam', 'Duga', 'Duga', '9832082915', None, 'dugaschool@gmail.com', None, 'Urban Area', None, '1828', 52.0, 0.0, 0.5, 'Recognized', 'c.b.s.e.', None, 'Class 1', 'Class 10', 'C.B.S.E.'), (5, 'East', 'S0856', 'EASWARAMMA SAI GURUKOOL ACCADEMY', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'PS', 'Private (Unaided)', 'RALUNG', 'Gangtok', 'West Pandam', 'Central Pendam', 'West Pendam', 'Ralang', 'West Pendam', '9733056624', None, None, None, 'Urban Area', None, '40179.66805555556', 0.0, 0.2, 0.2, 'Recognized', None, None, 'Class 1', 'Class 5', None), (6, 'East', 'S0870', 'ETERNAL ENGLISH SCHOOL, WEST PENDAM', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'PS', 'Private (Unaided)', 'SAKHU WEST PENDAM', 'Gangtok', 'West Pandam', 'West Pendam', 'West Pendam', 'Sakhu', 'Sakhu Busty', '9734190544', None, None, None, 'Urban Area', None, '37300.66805555556', 42.0, 3.0, 4.0, 'Recognized', 'HRDD OF SIKKIM', None, 'Class 1', 'Class 5', None), (7, 'East', 'S0157', 'KHANI GOAN GOVERNMENT PRIMARY SCHOOL', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'PS', 'State Govt.', 'WEST PENDAM', 'Gangtok', 'West Pandam', 'West Pendam', 'West Pendam', 'Khanigaon', 'West Pendam', '9832470263', None, None, None, 'Urban Area', '801801', '29587', 45.0, 5.0, 4.0, 'Recognized', 'State Govt.', None, 'Class 1', 'Class 5', 'C.B.S.E.')  ... displaying 10 of 1249 total bound parameter sets ...  (1247, 'West', 'S0340', 'TINGTING GAON GOVERNMENT PRIMARY SCHOOL', 'Yuksom Brc', 'Yuksom Government Secondary School', 'PS', 'State Govt.', 'TING TING GAON', 'Gyalshing', 'Yoksam-Tashiding', 'Yoksam', 'Yuksom', 'Tingting', 'Yuksom', '9593377402', None, None, None, 'Urban Area', '100282', '29587', 36.0, 3.0, 6.0, 'Recognized', 'STATE GOVERNMENT', None, 'Class 1', 'Class 5', None), (1248, 'West', 'S0542', 'TSONG GOVERNMENT PRIMARY SCHOOL', 'Yuksom Brc', 'Yuksom Government Secondary School', 'PS', 'State Govt.', 'TSONG', 'Gyalshing', 'Yoksam-Tashiding', 'Yoksam', 'Yuksom', 'Yoksam', 'Yuksom', None, None, None, None, 'Urban Area', None, '28176', 40.0, 7.0, 8.0, 'Recognized', 'State Government', None, 'Class 1', 'Class 5', 'C.B.S.E.')]

2024-05-23 19:12:33,062 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

1249

## SELECT & FROM

1. Get the EstablishmentName, SchoolLevel, and Website columns.

We can actually use Pandas to run SQL queries! To do this, we write a SQL query in a multi-line string. Simply replace the text in the multi-line string below with your SQL query and run the cell to query your data.

In [6]:
# Write your SQL query in this string
sql = """
SELECT EstablishmentName, SchoolLevel, Website
FROM school_details;
"""

# Read the sql query into pandas to view the results
pd.read_sql_query(sql, engine)

2024-05-23 19:15:27,175 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2024-05-23 19:15:27,180 INFO sqlalchemy.engine.Engine
SELECT EstablishmentName, SchoolLevel, Website
FROM school_details;

INFO:sqlalchemy.engine.Engine:
SELECT EstablishmentName, SchoolLevel, Website
FROM school_details;

2024-05-23 19:15:27,192 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-05-23 19:15:27,207 INFO sqlalchemy.engine.Engine ROLLBACK

INFO:sqlalchemy.engine.Engine:ROLLBACK

,EstablishmentName,SchoolLevel,Website
0,BUDANG GOVERNMENT PRIMARY SCHOOL (E),PS,None
1,CENTRAL PENDAM GOVERNMENT SENIOR SECONDARY SCHOOL,SSS,None
2,"CENTRAL POINT ACADEMY, CENTRAL PENDAM",SS,www.facebook.com/khanalkeshav (Group-CPA)
3,CHEURIBOTEY GOVERNMENT JUNIOR HIGH SCHOOL (E),JHS,None
4,DUGA GOVERNMENT SECONDARY SCHOOL,SS,None
...,...,...,...
1244,MANGSABONG GOVERNMENT PRIMARY SCHOOL,PS,None
1245,MANGTABONG GOVERNMENT PRIMARY SCHOOL(SSA),PS,None
1246,"NEW HORIZON ACADEMY, LASSO(TASHIDING)",PS,None
1247,TINGTING GAON GOVERNMENT PRIMARY SCHOOL,PS,None
1248,TSONG GOVERNMENT PRIMARY SCHOOL,PS,None

## WHERE

2. Display the EstablishmentName and DistrictHQDistance (in Km) for schools where the DistrictHQDistance (in Km) is more than 100 Km.

In [7]:
# Write your SQL query in this string
sql = """
SELECT EstablishmentName, `DistrictHQDistance (in Km)`
FROM school_details
WHERE `DistrictHQDistance (in Km)` > 10;
"""

# Read the sql query into pandas to view the results
pd.read_sql_query(sql, engine)

2024-05-23 19:15:52,875 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2024-05-23 19:15:52,880 INFO sqlalchemy.engine.Engine
SELECT EstablishmentName, `DistrictHQDistance (in Km)`
FROM school_details
WHERE `DistrictHQDistance (in Km)` > 10;

INFO:sqlalchemy.engine.Engine:
SELECT EstablishmentName, `DistrictHQDistance (in Km)`
FROM school_details
WHERE `DistrictHQDistance (in Km)` > 10;

2024-05-23 19:15:52,884 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-05-23 19:15:52,896 INFO sqlalchemy.engine.Engine ROLLBACK

INFO:sqlalchemy.engine.Engine:ROLLBACK

,EstablishmentName,DistrictHQDistance (in Km)
0,BUDANG GOVERNMENT PRIMARY SCHOOL (E),58.0
1,CENTRAL PENDAM GOVERNMENT SENIOR SECONDARY SCHOOL,50.0
2,"CENTRAL POINT ACADEMY, CENTRAL PENDAM",49.0
3,CHEURIBOTEY GOVERNMENT JUNIOR HIGH SCHOOL (E),60.0
4,DUGA GOVERNMENT SECONDARY SCHOOL,52.0
...,...,...
934,"LIFE VISION ACADEMY, YUKSAM",32.0
935,MANGSABONG GOVERNMENT PRIMARY SCHOOL,45.0
936,MANGTABONG GOVERNMENT PRIMARY SCHOOL(SSA),52.0
937,TINGTING GAON GOVERNMENT PRIMARY SCHOOL,36.0
938,TSONG GOVERNMENT PRIMARY SCHOOL,40.0

3. Display the EstablishmentName, SchoolLevel, DistrictHQDistance (in Km) for schools where the school level is "JHS."

In [ ]:
# Write your SQL query in this string
sql = """
Replace this text
with your query!
"""

# Read the sql query into pandas to view the results
 pd.read_sql_query(sql, engine)

## Wildcards & LIKE

4. Display the EstablishmentName, SchoolLevel, DistrictHQDistance (in Km) for schools where the name of the school contains the words "JUNIOR HIGH."

In [8]:
# Write your SQL query in this string
sql = """
SELECT EstablishmentName
FROM school_details
WHERE EstablishmentName LIKE '%Academy%';
"""

# Read the sql query into pandas to view the results
pd.read_sql_query(sql, engine)

2024-05-23 19:16:07,529 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2024-05-23 19:16:07,534 INFO sqlalchemy.engine.Engine
SELECT EstablishmentName
FROM school_details
WHERE EstablishmentName LIKE '%Academy%';

INFO:sqlalchemy.engine.Engine:
SELECT EstablishmentName
FROM school_details
WHERE EstablishmentName LIKE '%Academy%';

2024-05-23 19:16:07,537 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-05-23 19:16:07,543 INFO sqlalchemy.engine.Engine ROLLBACK

INFO:sqlalchemy.engine.Engine:ROLLBACK

                             EstablishmentName
0        CENTRAL POINT ACADEMY, CENTRAL PENDAM
1                        SUNRISE ACADEMY, DUGA
2                          NEW HORIZON ACADEMY
3                 NEW VISION ACADEMY, MAJHITAR
4            DE. NOBILE ACADEMY, ASSAM LINGZEY
..                                         ...
210       HIMALAYAN RADIANT ACADEMY, TASHIDING
211                  MARIGOLD ACADEMY, GANGYAP
212  MARIGOLD ACADEMY, POKHARI DARA, TASHIDING
213                LIFE VISION ACADEMY, YUKSAM
214      NEW HORIZON ACADEMY, LASSO(TASHIDING)

[215 rows x 1 columns]

## LIMIT & ORDER BY

5. Display the EstablishmentName, SchoolLevel, DistrictHQDistance (in Km) for schools where the name of the school starts with the letter "C." Sort the results alphabetically by school name and limit the results of the query to 10 rows.

In [9]:
# Write your SQL query in this string
sql = """
SELECT EstablishmentName, SchoolLevel, `DistrictHQDistance (in Km)`
FROM school_details
WHERE EstablishmentName LIKE 'C%'
ORDER BY EstablishmentName
LIMIT 10;
"""

# Read the sql query into pandas to view the results
pd.read_sql_query(sql, engine)

2024-05-23 19:16:24,541 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2024-05-23 19:16:24,545 INFO sqlalchemy.engine.Engine
SELECT EstablishmentName, SchoolLevel, `DistrictHQDistance (in Km)`
FROM school_details
WHERE EstablishmentName LIKE 'C%'
ORDER BY EstablishmentName
LIMIT 10;

INFO:sqlalchemy.engine.Engine:
SELECT EstablishmentName, SchoolLevel, `DistrictHQDistance (in Km)`
FROM school_details
WHERE EstablishmentName LIKE 'C%'
ORDER BY EstablishmentName
LIMIT 10;

2024-05-23 19:16:24,550 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-05-23 19:16:24,559 INFO sqlalchemy.engine.Engine ROLLBACK

INFO:sqlalchemy.engine.Engine:ROLLBACK

,EstablishmentName,SchoolLevel,DistrictHQDistance (in Km)
0,C.M.RAI GOVERNMENT SECONDARY SCHOOL (OMCHU),SS,26.0
1,"CANAAN SCHOOL, RANIPOOL",JHS,0.0
2,"CANARY BIRD ACADEMY, KARTOK",PS,38.0
3,"CAROL ACADEMY, YANGSUM UPPER BERFOK",JHS,50.0
4,CENTRAL MARTAM GOVERNMENT JUNIOR SCHOOL,JHS,50.0
5,CENTRAL PATUK GOVERNMENT PRIMARY SCHOOL,PS,48.0
6,CENTRAL PENDAM GOVERNMENT SENIOR SECONDARY SCHOOL,SSS,50.0
7,"CENTRAL POINT ACADEMY, CENTRAL PENDAM",SS,49.0
8,"CENTRAL SCHOOL FOR TIBETAN , RAVANGLA",JHS,26.0
9,CHAKUNG GOVERNMENT SENIOR SECONDARY SCHOOL,SSS,55.0

6. Display the names of schools in urban areas. Sort the results in reverse alphabetical order.

In [10]:
# Write your SQL query in this string
sql = """
SELECT EstablishmentName AS name
FROM school_details
WHERE LocatedInRuralOrUrban = 'Urban'
ORDER BY Establishmentname DESC;
"""

# Read the sql query into pandas to view the results
pd.read_sql_query(sql, engine)

2024-05-23 19:16:38,860 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2024-05-23 19:16:38,874 INFO sqlalchemy.engine.Engine
SELECT EstablishmentName AS name
FROM school_details
WHERE LocatedInRuralOrUrban = 'Urban'
ORDER BY Establishmentname DESC;

INFO:sqlalchemy.engine.Engine:
SELECT EstablishmentName AS name
FROM school_details
WHERE LocatedInRuralOrUrban = 'Urban'
ORDER BY Establishmentname DESC;

2024-05-23 19:16:38,892 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-05-23 19:16:38,912 INFO sqlalchemy.engine.Engine ROLLBACK

INFO:sqlalchemy.engine.Engine:ROLLBACK

Empty DataFrame
Columns: [name]
Index: []

## Aliasing

7. Repeat the previous query, but rename the column displayed to "name".

In [12]:
# Write your SQL query in this string
sql = """
SELECT EstablishmentName AS name
FROM school_details
WHERE LocatedInRuralOrUrban = 'Urban'
ORDER BY EstablishmentName DESC
"""

# Read the sql query into pandas to view the results
pd.read_sql_query(sql, engine)

2024-05-23 19:17:43,642 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2024-05-23 19:17:43,647 INFO sqlalchemy.engine.Engine
SELECT EstablishmentName AS name
FROM school_details
WHERE LocatedInRuralOrUrban = 'Urban'
ORDER BY EstablishmentName DESC

INFO:sqlalchemy.engine.Engine:
SELECT EstablishmentName AS name
FROM school_details
WHERE LocatedInRuralOrUrban = 'Urban'
ORDER BY EstablishmentName DESC

2024-05-23 19:17:43,650 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-05-23 19:17:43,657 INFO sqlalchemy.engine.Engine ROLLBACK

INFO:sqlalchemy.engine.Engine:ROLLBACK

Empty DataFrame
Columns: [name]
Index: []

In [ ]:
# Close the database connection
conn.close()